# Generated by Django 4.1.2 on 2022-12-13 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prime',
            new_name='price',
        ),
    ]
